name: WarpCost
main: com.toyz.warpcost.Main
version: 1.0
author: Toyz
description: A simple warp plugin which allows you to charge certain item as currency to get to the location
commands:
  warp:
    description: Go to a certain warped location
  setwarpprice:
    description: Create a warp that cost in-game item
    aliases: [makewarp, createwarp, pricewarp]
  setwarp:
    description: Create a free warp
    aliases: [freewarp, setw, sw]
  delwarp:
    description: Delete a warp

permissions:
  warp.make.free:
    description: Allows the user to create a free warp
    default: op
  warp.make.cost:
    description: Allows the user with this perm to make a warp
    default: op
  warp.remove:
    description: Allows the user to delete a warp
    default: op
  warp.go:
    description: Allows the user to use the warp command
    default: op